# Generated by Django 3.2.18 on 2023-04-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futurehomeapp', '0009_auto_20230415_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
