# Generated by Django 3.2.18 on 2023-04-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futurehomeapp', '0011_booking_profilepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePage',
        ),
    ]
