# Generated by Django 3.2.18 on 2023-04-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futurehomeapp', '0012_delete_profilepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='body',
            new_name='text',
        ),
    ]
