# Generated by Django 3.2.18 on 2023-04-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futurehomeapp', '0013_rename_body_booking_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
