# Generated by Django 3.2.18 on 2023-04-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futurehomeapp', '0015_question_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='parent',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('replied_on', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='futurehomeapp.question')),
            ],
            options={
                'ordering': ['replied_on'],
            },
        ),
    ]
